version: '3.8'

services:
  postgres:
    image: postgres:16.3
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=1234mudar
      - POSTGRES_PASSWORD=1234mudar
      - POSTGRES_DB=estoquenassau
