version: '4.39'

services:
  postgres:
    image: postgres:17.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=123mudar
      - POSTGRES_PASSWORD=123mudar
      - POSTGRES_DB=dbestoque
